return {
  "abomasnow-mega":
    "https://play.pokemonshowdown.com/audio/cries/abomasnow-mega.mp3",
  abomasnow: "https://play.pokemonshowdown.com/audio/cries/abomasnow.mp3",
  abra: "https://play.pokemonshowdown.com/audio/cries/abra.mp3",
  "absol-mega": "https://play.pokemonshowdown.com/audio/cries/absol-mega.mp3",
  absol: "https://play.pokemonshowdown.com/audio/cries/absol.mp3",
  accelgor: "https://play.pokemonshowdown.com/audio/cries/accelgor.mp3",
  aegislash: "https://play.pokemonshowdown.com/audio/cries/aegislash.mp3",
  "aerodactyl-mega":
    "https://play.pokemonshowdown.com/audio/cries/aerodactyl-mega.mp3",
  aerodactyl: "https://play.pokemonshowdown.com/audio/cries/aerodactyl.mp3",
  "aggron-mega": "https://play.pokemonshowdown.com/audio/cries/aggron-mega.mp3",
  aggron: "https://play.pokemonshowdown.com/audio/cries/aggron.mp3",
  aipom: "https://play.pokemonshowdown.com/audio/cries/aipom.mp3",
  "alakazam-mega":
    "https://play.pokemonshowdown.com/audio/cries/alakazam-mega.mp3",
  alakazam: "https://play.pokemonshowdown.com/audio/cries/alakazam.mp3",
  alcremie: "https://play.pokemonshowdown.com/audio/cries/alcremie.mp3",
  alomomola: "https://play.pokemonshowdown.com/audio/cries/alomomola.mp3",
  "altaria-mega":
    "https://play.pokemonshowdown.com/audio/cries/altaria-mega.mp3",
  altaria: "https://play.pokemonshowdown.com/audio/cries/altaria.mp3",
  amaura: "https://play.pokemonshowdown.com/audio/cries/amaura.mp3",
  ambipom: "https://play.pokemonshowdown.com/audio/cries/ambipom.mp3",
  amoonguss: "https://play.pokemonshowdown.com/audio/cries/amoonguss.mp3",
  "ampharos-mega":
    "https://play.pokemonshowdown.com/audio/cries/ampharos-mega.mp3",
  ampharos: "https://play.pokemonshowdown.com/audio/cries/ampharos.mp3",
  anorith: "https://play.pokemonshowdown.com/audio/cries/anorith.mp3",
  appletun: "https://play.pokemonshowdown.com/audio/cries/appletun.mp3",
  applin: "https://play.pokemonshowdown.com/audio/cries/applin.mp3",
  araquanid: "https://play.pokemonshowdown.com/audio/cries/araquanid.mp3",
  arbok: "https://play.pokemonshowdown.com/audio/cries/arbok.mp3",
  arcanine: "https://play.pokemonshowdown.com/audio/cries/arcanine.mp3",
  arceus: "https://play.pokemonshowdown.com/audio/cries/arceus.mp3",
  archen: "https://play.pokemonshowdown.com/audio/cries/archen.mp3",
  archeops: "https://play.pokemonshowdown.com/audio/cries/archeops.mp3",
  arctovish: "https://play.pokemonshowdown.com/audio/cries/arctovish.mp3",
  arctozolt: "https://play.pokemonshowdown.com/audio/cries/arctozolt.mp3",
  argalis: "https://play.pokemonshowdown.com/audio/cries/argalis.mp3",
  arghonaut: "https://play.pokemonshowdown.com/audio/cries/arghonaut.mp3",
  ariados: "https://play.pokemonshowdown.com/audio/cries/ariados.mp3",
  armaldo: "https://play.pokemonshowdown.com/audio/cries/armaldo.mp3",
  aromatisse: "https://play.pokemonshowdown.com/audio/cries/aromatisse.mp3",
  aron: "https://play.pokemonshowdown.com/audio/cries/aron.mp3",
  arrokuda: "https://play.pokemonshowdown.com/audio/cries/arrokuda.mp3",
  articuno: "https://play.pokemonshowdown.com/audio/cries/articuno.mp3",
  astrolotl: "https://play.pokemonshowdown.com/audio/cries/astrolotl.mp3",
  "audino-mega": "https://play.pokemonshowdown.com/audio/cries/audino-mega.mp3",
  audino: "https://play.pokemonshowdown.com/audio/cries/audino.mp3",
  aurorus: "https://play.pokemonshowdown.com/audio/cries/aurorus.mp3",
  aurumoth: "https://play.pokemonshowdown.com/audio/cries/aurumoth.mp3",
  avalugg: "https://play.pokemonshowdown.com/audio/cries/avalugg.mp3",
  axew: "https://play.pokemonshowdown.com/audio/cries/axew.mp3",
  azelf: "https://play.pokemonshowdown.com/audio/cries/azelf.mp3",
  azumarill: "https://play.pokemonshowdown.com/audio/cries/azumarill.mp3",
  azurill: "https://play.pokemonshowdown.com/audio/cries/azurill.mp3",
  bagon: "https://play.pokemonshowdown.com/audio/cries/bagon.mp3",
  baltoy: "https://play.pokemonshowdown.com/audio/cries/baltoy.mp3",
  "banette-mega":
    "https://play.pokemonshowdown.com/audio/cries/banette-mega.mp3",
  banette: "https://play.pokemonshowdown.com/audio/cries/banette.mp3",
  barbaracle: "https://play.pokemonshowdown.com/audio/cries/barbaracle.mp3",
  barboach: "https://play.pokemonshowdown.com/audio/cries/barboach.mp3",
  barraskewda: "https://play.pokemonshowdown.com/audio/cries/barraskewda.mp3",
  basculin: "https://play.pokemonshowdown.com/audio/cries/basculin.mp3",
  bastiodon: "https://play.pokemonshowdown.com/audio/cries/bastiodon.mp3",
  bayleef: "https://play.pokemonshowdown.com/audio/cries/bayleef.mp3",
  beartic: "https://play.pokemonshowdown.com/audio/cries/beartic.mp3",
  beautifly: "https://play.pokemonshowdown.com/audio/cries/beautifly.mp3",
  "beedrill-mega":
    "https://play.pokemonshowdown.com/audio/cries/beedrill-mega.mp3",
  beedrill: "https://play.pokemonshowdown.com/audio/cries/beedrill.mp3",
  beheeyem: "https://play.pokemonshowdown.com/audio/cries/beheeyem.mp3",
  beldum: "https://play.pokemonshowdown.com/audio/cries/beldum.mp3",
  bellossom: "https://play.pokemonshowdown.com/audio/cries/bellossom.mp3",
  bellsprout: "https://play.pokemonshowdown.com/audio/cries/bellsprout.mp3",
  bergmite: "https://play.pokemonshowdown.com/audio/cries/bergmite.mp3",
  bewear: "https://play.pokemonshowdown.com/audio/cries/bewear.mp3",
  bibarel: "https://play.pokemonshowdown.com/audio/cries/bibarel.mp3",
  bidoof: "https://play.pokemonshowdown.com/audio/cries/bidoof.mp3",
  binacle: "https://play.pokemonshowdown.com/audio/cries/binacle.mp3",
  bisharp: "https://play.pokemonshowdown.com/audio/cries/bisharp.mp3",
  blacephalon: "https://play.pokemonshowdown.com/audio/cries/blacephalon.mp3",
  "blastoise-mega":
    "https://play.pokemonshowdown.com/audio/cries/blastoise-mega.mp3",
  blastoise: "https://play.pokemonshowdown.com/audio/cries/blastoise.mp3",
  "blaziken-mega":
    "https://play.pokemonshowdown.com/audio/cries/blaziken-mega.mp3",
  blaziken: "https://play.pokemonshowdown.com/audio/cries/blaziken.mp3",
  blipbug: "https://play.pokemonshowdown.com/audio/cries/blipbug.mp3",
  blissey: "https://play.pokemonshowdown.com/audio/cries/blissey.mp3",
  blitzle: "https://play.pokemonshowdown.com/audio/cries/blitzle.mp3",
  boldore: "https://play.pokemonshowdown.com/audio/cries/boldore.mp3",
  boltund: "https://play.pokemonshowdown.com/audio/cries/boltund.mp3",
  bonsly: "https://play.pokemonshowdown.com/audio/cries/bonsly.mp3",
  bouffalant: "https://play.pokemonshowdown.com/audio/cries/bouffalant.mp3",
  bounsweet: "https://play.pokemonshowdown.com/audio/cries/bounsweet.mp3",
  braixen: "https://play.pokemonshowdown.com/audio/cries/braixen.mp3",
  brattler: "https://play.pokemonshowdown.com/audio/cries/brattler.mp3",
  braviary: "https://play.pokemonshowdown.com/audio/cries/braviary.mp3",
  breezi: "https://play.pokemonshowdown.com/audio/cries/breezi.mp3",
  breloom: "https://play.pokemonshowdown.com/audio/cries/breloom.mp3",
  brionne: "https://play.pokemonshowdown.com/audio/cries/brionne.mp3",
  bronzong: "https://play.pokemonshowdown.com/audio/cries/bronzong.mp3",
  bronzor: "https://play.pokemonshowdown.com/audio/cries/bronzor.mp3",
  bruxish: "https://play.pokemonshowdown.com/audio/cries/bruxish.mp3",
  budew: "https://play.pokemonshowdown.com/audio/cries/budew.mp3",
  buizel: "https://play.pokemonshowdown.com/audio/cries/buizel.mp3",
  bulbasaur: "https://play.pokemonshowdown.com/audio/cries/bulbasaur.mp3",
  buneary: "https://play.pokemonshowdown.com/audio/cries/buneary.mp3",
  bunnelby: "https://play.pokemonshowdown.com/audio/cries/bunnelby.mp3",
  burmy: "https://play.pokemonshowdown.com/audio/cries/burmy.mp3",
  butterfree: "https://play.pokemonshowdown.com/audio/cries/butterfree.mp3",
  buzzwole: "https://play.pokemonshowdown.com/audio/cries/buzzwole.mp3",
  cacnea: "https://play.pokemonshowdown.com/audio/cries/cacnea.mp3",
  cacturne: "https://play.pokemonshowdown.com/audio/cries/cacturne.mp3",
  caimanoe: "https://play.pokemonshowdown.com/audio/cries/caimanoe.mp3",
  "calyrex-ice": "https://play.pokemonshowdown.com/audio/cries/calyrex-ice.mp3",
  "calyrex-shadow":
    "https://play.pokemonshowdown.com/audio/cries/calyrex-shadow.mp3",
  calyrex: "https://play.pokemonshowdown.com/audio/cries/calyrex.mp3",
  "camerupt-mega":
    "https://play.pokemonshowdown.com/audio/cries/camerupt-mega.mp3",
  camerupt: "https://play.pokemonshowdown.com/audio/cries/camerupt.mp3",
  carbink: "https://play.pokemonshowdown.com/audio/cries/carbink.mp3",
  caribolt: "https://play.pokemonshowdown.com/audio/cries/caribolt.mp3",
  carkol: "https://play.pokemonshowdown.com/audio/cries/carkol.mp3",
  carnivine: "https://play.pokemonshowdown.com/audio/cries/carnivine.mp3",
  carracosta: "https://play.pokemonshowdown.com/audio/cries/carracosta.mp3",
  carvanha: "https://play.pokemonshowdown.com/audio/cries/carvanha.mp3",
  cascoon: "https://play.pokemonshowdown.com/audio/cries/cascoon.mp3",
  castform: "https://play.pokemonshowdown.com/audio/cries/castform.mp3",
  caterpie: "https://play.pokemonshowdown.com/audio/cries/caterpie.mp3",
  cawdet: "https://play.pokemonshowdown.com/audio/cries/cawdet.mp3",
  cawmodore: "https://play.pokemonshowdown.com/audio/cries/cawmodore.mp3",
  celebi: "https://play.pokemonshowdown.com/audio/cries/celebi.mp3",
  celesteela: "https://play.pokemonshowdown.com/audio/cries/celesteela.mp3",
  centiskorch: "https://play.pokemonshowdown.com/audio/cries/centiskorch.mp3",
  chandelure: "https://play.pokemonshowdown.com/audio/cries/chandelure.mp3",
  chansey: "https://play.pokemonshowdown.com/audio/cries/chansey.mp3",
  "charizard-megax":
    "https://play.pokemonshowdown.com/audio/cries/charizard-megax.mp3",
  "charizard-megay":
    "https://play.pokemonshowdown.com/audio/cries/charizard-megay.mp3",
  charizard: "https://play.pokemonshowdown.com/audio/cries/charizard.mp3",
  charjabug: "https://play.pokemonshowdown.com/audio/cries/charjabug.mp3",
  charmander: "https://play.pokemonshowdown.com/audio/cries/charmander.mp3",
  charmeleon: "https://play.pokemonshowdown.com/audio/cries/charmeleon.mp3",
  chatot: "https://play.pokemonshowdown.com/audio/cries/chatot.mp3",
  cherrim: "https://play.pokemonshowdown.com/audio/cries/cherrim.mp3",
  cherubi: "https://play.pokemonshowdown.com/audio/cries/cherubi.mp3",
  chesnaught: "https://play.pokemonshowdown.com/audio/cries/chesnaught.mp3",
  chespin: "https://play.pokemonshowdown.com/audio/cries/chespin.mp3",
  chewtle: "https://play.pokemonshowdown.com/audio/cries/chewtle.mp3",
  chikorita: "https://play.pokemonshowdown.com/audio/cries/chikorita.mp3",
  chimchar: "https://play.pokemonshowdown.com/audio/cries/chimchar.mp3",
  chimecho: "https://play.pokemonshowdown.com/audio/cries/chimecho.mp3",
  chinchou: "https://play.pokemonshowdown.com/audio/cries/chinchou.mp3",
  chingling: "https://play.pokemonshowdown.com/audio/cries/chingling.mp3",
  chromera: "https://play.pokemonshowdown.com/audio/cries/chromera.mp3",
  cinccino: "https://play.pokemonshowdown.com/audio/cries/cinccino.mp3",
  cinderace: "https://play.pokemonshowdown.com/audio/cries/cinderace.mp3",
  clamperl: "https://play.pokemonshowdown.com/audio/cries/clamperl.mp3",
  clauncher: "https://play.pokemonshowdown.com/audio/cries/clauncher.mp3",
  clawitzer: "https://play.pokemonshowdown.com/audio/cries/clawitzer.mp3",
  claydol: "https://play.pokemonshowdown.com/audio/cries/claydol.mp3",
  clefable: "https://play.pokemonshowdown.com/audio/cries/clefable.mp3",
  clefairy: "https://play.pokemonshowdown.com/audio/cries/clefairy.mp3",
  cleffa: "https://play.pokemonshowdown.com/audio/cries/cleffa.mp3",
  clobbopus: "https://play.pokemonshowdown.com/audio/cries/clobbopus.mp3",
  cloyster: "https://play.pokemonshowdown.com/audio/cries/cloyster.mp3",
  coalossal: "https://play.pokemonshowdown.com/audio/cries/coalossal.mp3",
  cobalion: "https://play.pokemonshowdown.com/audio/cries/cobalion.mp3",
  cofagrigus: "https://play.pokemonshowdown.com/audio/cries/cofagrigus.mp3",
  colosshale: "https://play.pokemonshowdown.com/audio/cries/colosshale.mp3",
  colossoil: "https://play.pokemonshowdown.com/audio/cries/colossoil.mp3",
  combee: "https://play.pokemonshowdown.com/audio/cries/combee.mp3",
  combusken: "https://play.pokemonshowdown.com/audio/cries/combusken.mp3",
  comfey: "https://play.pokemonshowdown.com/audio/cries/comfey.mp3",
  conkeldurr: "https://play.pokemonshowdown.com/audio/cries/conkeldurr.mp3",
  copperajah: "https://play.pokemonshowdown.com/audio/cries/copperajah.mp3",
  coribalis: "https://play.pokemonshowdown.com/audio/cries/coribalis.mp3",
  corphish: "https://play.pokemonshowdown.com/audio/cries/corphish.mp3",
  corsola: "https://play.pokemonshowdown.com/audio/cries/corsola.mp3",
  corviknight: "https://play.pokemonshowdown.com/audio/cries/corviknight.mp3",
  corvisquire: "https://play.pokemonshowdown.com/audio/cries/corvisquire.mp3",
  cosmoem: "https://play.pokemonshowdown.com/audio/cries/cosmoem.mp3",
  cosmog: "https://play.pokemonshowdown.com/audio/cries/cosmog.mp3",
  cottonee: "https://play.pokemonshowdown.com/audio/cries/cottonee.mp3",
  crabominable: "https://play.pokemonshowdown.com/audio/cries/crabominable.mp3",
  crabrawler: "https://play.pokemonshowdown.com/audio/cries/crabrawler.mp3",
  cradily: "https://play.pokemonshowdown.com/audio/cries/cradily.mp3",
  "cramorant-gorging":
    "https://play.pokemonshowdown.com/audio/cries/cramorant-gorging.mp3",
  "cramorant-gulping":
    "https://play.pokemonshowdown.com/audio/cries/cramorant-gulping.mp3",
  cramorant: "https://play.pokemonshowdown.com/audio/cries/cramorant.mp3",
  cranidos: "https://play.pokemonshowdown.com/audio/cries/cranidos.mp3",
  crawdaunt: "https://play.pokemonshowdown.com/audio/cries/crawdaunt.mp3",
  cresselia: "https://play.pokemonshowdown.com/audio/cries/cresselia.mp3",
  croagunk: "https://play.pokemonshowdown.com/audio/cries/croagunk.mp3",
  crobat: "https://play.pokemonshowdown.com/audio/cries/crobat.mp3",
  croconaw: "https://play.pokemonshowdown.com/audio/cries/croconaw.mp3",
  "crucibelle-mega":
    "https://play.pokemonshowdown.com/audio/cries/crucibelle-mega.mp3",
  crucibelle: "https://play.pokemonshowdown.com/audio/cries/crucibelle.mp3",
  crustle: "https://play.pokemonshowdown.com/audio/cries/crustle.mp3",
  cryogonal: "https://play.pokemonshowdown.com/audio/cries/cryogonal.mp3",
  cubchoo: "https://play.pokemonshowdown.com/audio/cries/cubchoo.mp3",
  cubone: "https://play.pokemonshowdown.com/audio/cries/cubone.mp3",
  cufant: "https://play.pokemonshowdown.com/audio/cries/cufant.mp3",
  cupra: "https://play.pokemonshowdown.com/audio/cries/cupra.mp3",
  cursola: "https://play.pokemonshowdown.com/audio/cries/cursola.mp3",
  cutiefly: "https://play.pokemonshowdown.com/audio/cries/cutiefly.mp3",
  cyclohm: "https://play.pokemonshowdown.com/audio/cries/cyclohm.mp3",
  cyndaquil: "https://play.pokemonshowdown.com/audio/cries/cyndaquil.mp3",
  darkrai: "https://play.pokemonshowdown.com/audio/cries/darkrai.mp3",
  darmanitan: "https://play.pokemonshowdown.com/audio/cries/darmanitan.mp3",
  dartrix: "https://play.pokemonshowdown.com/audio/cries/dartrix.mp3",
  darumaka: "https://play.pokemonshowdown.com/audio/cries/darumaka.mp3",
  decidueye: "https://play.pokemonshowdown.com/audio/cries/decidueye.mp3",
  dedenne: "https://play.pokemonshowdown.com/audio/cries/dedenne.mp3",
  deerling: "https://play.pokemonshowdown.com/audio/cries/deerling.mp3",
  deino: "https://play.pokemonshowdown.com/audio/cries/deino.mp3",
  delcatty: "https://play.pokemonshowdown.com/audio/cries/delcatty.mp3",
  delibird: "https://play.pokemonshowdown.com/audio/cries/delibird.mp3",
  delphox: "https://play.pokemonshowdown.com/audio/cries/delphox.mp3",
  deoxys: "https://play.pokemonshowdown.com/audio/cries/deoxys.mp3",
  dewgong: "https://play.pokemonshowdown.com/audio/cries/dewgong.mp3",
  dewott: "https://play.pokemonshowdown.com/audio/cries/dewott.mp3",
  dewpider: "https://play.pokemonshowdown.com/audio/cries/dewpider.mp3",
  dhelmise: "https://play.pokemonshowdown.com/audio/cries/dhelmise.mp3",
  dialga: "https://play.pokemonshowdown.com/audio/cries/dialga.mp3",
  "diancie-mega":
    "https://play.pokemonshowdown.com/audio/cries/diancie-mega.mp3",
  diancie: "https://play.pokemonshowdown.com/audio/cries/diancie.mp3",
  diggersby: "https://play.pokemonshowdown.com/audio/cries/diggersby.mp3",
  diglett: "https://play.pokemonshowdown.com/audio/cries/diglett.mp3",
  ditto: "https://play.pokemonshowdown.com/audio/cries/ditto.mp3",
  dodrio: "https://play.pokemonshowdown.com/audio/cries/dodrio.mp3",
  doduo: "https://play.pokemonshowdown.com/audio/cries/doduo.mp3",
  donphan: "https://play.pokemonshowdown.com/audio/cries/donphan.mp3",
  dorsoil: "https://play.pokemonshowdown.com/audio/cries/dorsoil.mp3",
  dottler: "https://play.pokemonshowdown.com/audio/cries/dottler.mp3",
  doublade: "https://play.pokemonshowdown.com/audio/cries/doublade.mp3",
  dracovish: "https://play.pokemonshowdown.com/audio/cries/dracovish.mp3",
  dracozolt: "https://play.pokemonshowdown.com/audio/cries/dracozolt.mp3",
  dragalge: "https://play.pokemonshowdown.com/audio/cries/dragalge.mp3",
  dragapult: "https://play.pokemonshowdown.com/audio/cries/dragapult.mp3",
  dragonair: "https://play.pokemonshowdown.com/audio/cries/dragonair.mp3",
  dragonite: "https://play.pokemonshowdown.com/audio/cries/dragonite.mp3",
  drakloak: "https://play.pokemonshowdown.com/audio/cries/drakloak.mp3",
  drampa: "https://play.pokemonshowdown.com/audio/cries/drampa.mp3",
  drapion: "https://play.pokemonshowdown.com/audio/cries/drapion.mp3",
  dratini: "https://play.pokemonshowdown.com/audio/cries/dratini.mp3",
  drednaw: "https://play.pokemonshowdown.com/audio/cries/drednaw.mp3",
  dreepy: "https://play.pokemonshowdown.com/audio/cries/dreepy.mp3",
  drifblim: "https://play.pokemonshowdown.com/audio/cries/drifblim.mp3",
  drifloon: "https://play.pokemonshowdown.com/audio/cries/drifloon.mp3",
  drilbur: "https://play.pokemonshowdown.com/audio/cries/drilbur.mp3",
  drizzile: "https://play.pokemonshowdown.com/audio/cries/drizzile.mp3",
  drowzee: "https://play.pokemonshowdown.com/audio/cries/drowzee.mp3",
  druddigon: "https://play.pokemonshowdown.com/audio/cries/druddigon.mp3",
  dubwool: "https://play.pokemonshowdown.com/audio/cries/dubwool.mp3",
  ducklett: "https://play.pokemonshowdown.com/audio/cries/ducklett.mp3",
  dugtrio: "https://play.pokemonshowdown.com/audio/cries/dugtrio.mp3",
  dunsparce: "https://play.pokemonshowdown.com/audio/cries/dunsparce.mp3",
  duohm: "https://play.pokemonshowdown.com/audio/cries/duohm.mp3",
  duosion: "https://play.pokemonshowdown.com/audio/cries/duosion.mp3",
  duraludon: "https://play.pokemonshowdown.com/audio/cries/duraludon.mp3",
  durant: "https://play.pokemonshowdown.com/audio/cries/durant.mp3",
  dusclops: "https://play.pokemonshowdown.com/audio/cries/dusclops.mp3",
  dusknoir: "https://play.pokemonshowdown.com/audio/cries/dusknoir.mp3",
  duskull: "https://play.pokemonshowdown.com/audio/cries/duskull.mp3",
  dustox: "https://play.pokemonshowdown.com/audio/cries/dustox.mp3",
  dwebble: "https://play.pokemonshowdown.com/audio/cries/dwebble.mp3",
  eelektrik: "https://play.pokemonshowdown.com/audio/cries/eelektrik.mp3",
  eelektross: "https://play.pokemonshowdown.com/audio/cries/eelektross.mp3",
  "eevee-starter":
    "https://play.pokemonshowdown.com/audio/cries/eevee-starter.mp3",
  eevee: "https://play.pokemonshowdown.com/audio/cries/eevee.mp3",
  "eiscue-noice":
    "https://play.pokemonshowdown.com/audio/cries/eiscue-noice.mp3",
  eiscue: "https://play.pokemonshowdown.com/audio/cries/eiscue.mp3",
  ekans: "https://play.pokemonshowdown.com/audio/cries/ekans.mp3",
  eldegoss: "https://play.pokemonshowdown.com/audio/cries/eldegoss.mp3",
  electabuzz: "https://play.pokemonshowdown.com/audio/cries/electabuzz.mp3",
  electivire: "https://play.pokemonshowdown.com/audio/cries/electivire.mp3",
  electrelk: "https://play.pokemonshowdown.com/audio/cries/electrelk.mp3",
  electrike: "https://play.pokemonshowdown.com/audio/cries/electrike.mp3",
  electrode: "https://play.pokemonshowdown.com/audio/cries/electrode.mp3",
  elekid: "https://play.pokemonshowdown.com/audio/cries/elekid.mp3",
  elgyem: "https://play.pokemonshowdown.com/audio/cries/elgyem.mp3",
  embirch: "https://play.pokemonshowdown.com/audio/cries/embirch.mp3",
  emboar: "https://play.pokemonshowdown.com/audio/cries/emboar.mp3",
  emolga: "https://play.pokemonshowdown.com/audio/cries/emolga.mp3",
  empoleon: "https://play.pokemonshowdown.com/audio/cries/empoleon.mp3",
  entei: "https://play.pokemonshowdown.com/audio/cries/entei.mp3",
  equilibra: "https://play.pokemonshowdown.com/audio/cries/equilibra.mp3",
  escavalier: "https://play.pokemonshowdown.com/audio/cries/escavalier.mp3",
  espeon: "https://play.pokemonshowdown.com/audio/cries/espeon.mp3",
  espurr: "https://play.pokemonshowdown.com/audio/cries/espurr.mp3",
  "eternatus-eternamax":
    "https://play.pokemonshowdown.com/audio/cries/eternatus-eternamax.mp3",
  eternatus: "https://play.pokemonshowdown.com/audio/cries/eternatus.mp3",
  excadrill: "https://play.pokemonshowdown.com/audio/cries/excadrill.mp3",
  exeggcute: "https://play.pokemonshowdown.com/audio/cries/exeggcute.mp3",
  exeggutor: "https://play.pokemonshowdown.com/audio/cries/exeggutor.mp3",
  exploud: "https://play.pokemonshowdown.com/audio/cries/exploud.mp3",
  falinks: "https://play.pokemonshowdown.com/audio/cries/falinks.mp3",
  farfetchd: "https://play.pokemonshowdown.com/audio/cries/farfetchd.mp3",
  fawnifer: "https://play.pokemonshowdown.com/audio/cries/fawnifer.mp3",
  fearow: "https://play.pokemonshowdown.com/audio/cries/fearow.mp3",
  feebas: "https://play.pokemonshowdown.com/audio/cries/feebas.mp3",
  fennekin: "https://play.pokemonshowdown.com/audio/cries/fennekin.mp3",
  feraligatr: "https://play.pokemonshowdown.com/audio/cries/feraligatr.mp3",
  ferroseed: "https://play.pokemonshowdown.com/audio/cries/ferroseed.mp3",
  ferrothorn: "https://play.pokemonshowdown.com/audio/cries/ferrothorn.mp3",
  fidgit: "https://play.pokemonshowdown.com/audio/cries/fidgit.mp3",
  finneon: "https://play.pokemonshowdown.com/audio/cries/finneon.mp3",
  flaaffy: "https://play.pokemonshowdown.com/audio/cries/flaaffy.mp3",
  flabebe: "https://play.pokemonshowdown.com/audio/cries/flabebe.mp3",
  flapple: "https://play.pokemonshowdown.com/audio/cries/flapple.mp3",
  flarelm: "https://play.pokemonshowdown.com/audio/cries/flarelm.mp3",
  flareon: "https://play.pokemonshowdown.com/audio/cries/flareon.mp3",
  fletchinder: "https://play.pokemonshowdown.com/audio/cries/fletchinder.mp3",
  fletchling: "https://play.pokemonshowdown.com/audio/cries/fletchling.mp3",
  floatoy: "https://play.pokemonshowdown.com/audio/cries/floatoy.mp3",
  floatzel: "https://play.pokemonshowdown.com/audio/cries/floatzel.mp3",
  "floette-eternal":
    "https://play.pokemonshowdown.com/audio/cries/floette-eternal.mp3",
  floette: "https://play.pokemonshowdown.com/audio/cries/floette.mp3",
  florges: "https://play.pokemonshowdown.com/audio/cries/florges.mp3",
  flygon: "https://play.pokemonshowdown.com/audio/cries/flygon.mp3",
  fomantis: "https://play.pokemonshowdown.com/audio/cries/fomantis.mp3",
  foongus: "https://play.pokemonshowdown.com/audio/cries/foongus.mp3",
  forretress: "https://play.pokemonshowdown.com/audio/cries/forretress.mp3",
  fraxure: "https://play.pokemonshowdown.com/audio/cries/fraxure.mp3",
  frillish: "https://play.pokemonshowdown.com/audio/cries/frillish.mp3",
  froakie: "https://play.pokemonshowdown.com/audio/cries/froakie.mp3",
  frogadier: "https://play.pokemonshowdown.com/audio/cries/frogadier.mp3",
  froslass: "https://play.pokemonshowdown.com/audio/cries/froslass.mp3",
  frosmoth: "https://play.pokemonshowdown.com/audio/cries/frosmoth.mp3",
  furfrou: "https://play.pokemonshowdown.com/audio/cries/furfrou.mp3",
  furret: "https://play.pokemonshowdown.com/audio/cries/furret.mp3",
  gabite: "https://play.pokemonshowdown.com/audio/cries/gabite.mp3",
  "gallade-mega":
    "https://play.pokemonshowdown.com/audio/cries/gallade-mega.mp3",
  gallade: "https://play.pokemonshowdown.com/audio/cries/gallade.mp3",
  galvantula: "https://play.pokemonshowdown.com/audio/cries/galvantula.mp3",
  garbodor: "https://play.pokemonshowdown.com/audio/cries/garbodor.mp3",
  "garchomp-mega":
    "https://play.pokemonshowdown.com/audio/cries/garchomp-mega.mp3",
  garchomp: "https://play.pokemonshowdown.com/audio/cries/garchomp.mp3",
  "gardevoir-mega":
    "https://play.pokemonshowdown.com/audio/cries/gardevoir-mega.mp3",
  gardevoir: "https://play.pokemonshowdown.com/audio/cries/gardevoir.mp3",
  gastly: "https://play.pokemonshowdown.com/audio/cries/gastly.mp3",
  gastrodon: "https://play.pokemonshowdown.com/audio/cries/gastrodon.mp3",
  genesect: "https://play.pokemonshowdown.com/audio/cries/genesect.mp3",
  "gengar-mega": "https://play.pokemonshowdown.com/audio/cries/gengar-mega.mp3",
  gengar: "https://play.pokemonshowdown.com/audio/cries/gengar.mp3",
  geodude: "https://play.pokemonshowdown.com/audio/cries/geodude.mp3",
  gible: "https://play.pokemonshowdown.com/audio/cries/gible.mp3",
  gigalith: "https://play.pokemonshowdown.com/audio/cries/gigalith.mp3",
  girafarig: "https://play.pokemonshowdown.com/audio/cries/girafarig.mp3",
  giratina: "https://play.pokemonshowdown.com/audio/cries/giratina.mp3",
  glaceon: "https://play.pokemonshowdown.com/audio/cries/glaceon.mp3",
  "glalie-mega": "https://play.pokemonshowdown.com/audio/cries/glalie-mega.mp3",
  glalie: "https://play.pokemonshowdown.com/audio/cries/glalie.mp3",
  glameow: "https://play.pokemonshowdown.com/audio/cries/glameow.mp3",
  glastrier: "https://play.pokemonshowdown.com/audio/cries/glastrier.mp3",
  gligar: "https://play.pokemonshowdown.com/audio/cries/gligar.mp3",
  gliscor: "https://play.pokemonshowdown.com/audio/cries/gliscor.mp3",
  gloom: "https://play.pokemonshowdown.com/audio/cries/gloom.mp3",
  gogoat: "https://play.pokemonshowdown.com/audio/cries/gogoat.mp3",
  golbat: "https://play.pokemonshowdown.com/audio/cries/golbat.mp3",
  goldeen: "https://play.pokemonshowdown.com/audio/cries/goldeen.mp3",
  golduck: "https://play.pokemonshowdown.com/audio/cries/golduck.mp3",
  golem: "https://play.pokemonshowdown.com/audio/cries/golem.mp3",
  golett: "https://play.pokemonshowdown.com/audio/cries/golett.mp3",
  golisopod: "https://play.pokemonshowdown.com/audio/cries/golisopod.mp3",
  golurk: "https://play.pokemonshowdown.com/audio/cries/golurk.mp3",
  goodra: "https://play.pokemonshowdown.com/audio/cries/goodra.mp3",
  goomy: "https://play.pokemonshowdown.com/audio/cries/goomy.mp3",
  gorebyss: "https://play.pokemonshowdown.com/audio/cries/gorebyss.mp3",
  gossifleur: "https://play.pokemonshowdown.com/audio/cries/gossifleur.mp3",
  gothita: "https://play.pokemonshowdown.com/audio/cries/gothita.mp3",
  gothitelle: "https://play.pokemonshowdown.com/audio/cries/gothitelle.mp3",
  gothorita: "https://play.pokemonshowdown.com/audio/cries/gothorita.mp3",
  "gourgeist-super":
    "https://play.pokemonshowdown.com/audio/cries/gourgeist-super.mp3",
  gourgeist: "https://play.pokemonshowdown.com/audio/cries/gourgeist.mp3",
  granbull: "https://play.pokemonshowdown.com/audio/cries/granbull.mp3",
  grapploct: "https://play.pokemonshowdown.com/audio/cries/grapploct.mp3",
  graveler: "https://play.pokemonshowdown.com/audio/cries/graveler.mp3",
  greedent: "https://play.pokemonshowdown.com/audio/cries/greedent.mp3",
  greninja: "https://play.pokemonshowdown.com/audio/cries/greninja.mp3",
  grimer: "https://play.pokemonshowdown.com/audio/cries/grimer.mp3",
  grimmsnarl: "https://play.pokemonshowdown.com/audio/cries/grimmsnarl.mp3",
  grookey: "https://play.pokemonshowdown.com/audio/cries/grookey.mp3",
  grotle: "https://play.pokemonshowdown.com/audio/cries/grotle.mp3",
  "groudon-primal":
    "https://play.pokemonshowdown.com/audio/cries/groudon-primal.mp3",
  groudon: "https://play.pokemonshowdown.com/audio/cries/groudon.mp3",
  grovyle: "https://play.pokemonshowdown.com/audio/cries/grovyle.mp3",
  growlithe: "https://play.pokemonshowdown.com/audio/cries/growlithe.mp3",
  grubbin: "https://play.pokemonshowdown.com/audio/cries/grubbin.mp3",
  grumpig: "https://play.pokemonshowdown.com/audio/cries/grumpig.mp3",
  gulpin: "https://play.pokemonshowdown.com/audio/cries/gulpin.mp3",
  gumshoos: "https://play.pokemonshowdown.com/audio/cries/gumshoos.mp3",
  gurdurr: "https://play.pokemonshowdown.com/audio/cries/gurdurr.mp3",
  guzzlord: "https://play.pokemonshowdown.com/audio/cries/guzzlord.mp3",
  "gyarados-mega":
    "https://play.pokemonshowdown.com/audio/cries/gyarados-mega.mp3",
  gyarados: "https://play.pokemonshowdown.com/audio/cries/gyarados.mp3",
  hakamoo: "https://play.pokemonshowdown.com/audio/cries/hakamoo.mp3",
  happiny: "https://play.pokemonshowdown.com/audio/cries/happiny.mp3",
  hariyama: "https://play.pokemonshowdown.com/audio/cries/hariyama.mp3",
  hatenna: "https://play.pokemonshowdown.com/audio/cries/hatenna.mp3",
  hatterene: "https://play.pokemonshowdown.com/audio/cries/hatterene.mp3",
  hattrem: "https://play.pokemonshowdown.com/audio/cries/hattrem.mp3",
  haunter: "https://play.pokemonshowdown.com/audio/cries/haunter.mp3",
  hawlucha: "https://play.pokemonshowdown.com/audio/cries/hawlucha.mp3",
  haxorus: "https://play.pokemonshowdown.com/audio/cries/haxorus.mp3",
  heatmor: "https://play.pokemonshowdown.com/audio/cries/heatmor.mp3",
  heatran: "https://play.pokemonshowdown.com/audio/cries/heatran.mp3",
  heliolisk: "https://play.pokemonshowdown.com/audio/cries/heliolisk.mp3",
  helioptile: "https://play.pokemonshowdown.com/audio/cries/helioptile.mp3",
  "heracross-mega":
    "https://play.pokemonshowdown.com/audio/cries/heracross-mega.mp3",
  heracross: "https://play.pokemonshowdown.com/audio/cries/heracross.mp3",
  herdier: "https://play.pokemonshowdown.com/audio/cries/herdier.mp3",
  hippopotas: "https://play.pokemonshowdown.com/audio/cries/hippopotas.mp3",
  hippowdon: "https://play.pokemonshowdown.com/audio/cries/hippowdon.mp3",
  hitmonchan: "https://play.pokemonshowdown.com/audio/cries/hitmonchan.mp3",
  hitmonlee: "https://play.pokemonshowdown.com/audio/cries/hitmonlee.mp3",
  hitmontop: "https://play.pokemonshowdown.com/audio/cries/hitmontop.mp3",
  honchkrow: "https://play.pokemonshowdown.com/audio/cries/honchkrow.mp3",
  honedge: "https://play.pokemonshowdown.com/audio/cries/honedge.mp3",
  hooh: "https://play.pokemonshowdown.com/audio/cries/hooh.mp3",
  "hoopa-unbound":
    "https://play.pokemonshowdown.com/audio/cries/hoopa-unbound.mp3",
  hoopa: "https://play.pokemonshowdown.com/audio/cries/hoopa.mp3",
  hoothoot: "https://play.pokemonshowdown.com/audio/cries/hoothoot.mp3",
  hoppip: "https://play.pokemonshowdown.com/audio/cries/hoppip.mp3",
  horsea: "https://play.pokemonshowdown.com/audio/cries/horsea.mp3",
  "houndoom-mega":
    "https://play.pokemonshowdown.com/audio/cries/houndoom-mega.mp3",
  houndoom: "https://play.pokemonshowdown.com/audio/cries/houndoom.mp3",
  houndour: "https://play.pokemonshowdown.com/audio/cries/houndour.mp3",
  huntail: "https://play.pokemonshowdown.com/audio/cries/huntail.mp3",
  hydreigon: "https://play.pokemonshowdown.com/audio/cries/hydreigon.mp3",
  hypno: "https://play.pokemonshowdown.com/audio/cries/hypno.mp3",
  igglybuff: "https://play.pokemonshowdown.com/audio/cries/igglybuff.mp3",
  illumise: "https://play.pokemonshowdown.com/audio/cries/illumise.mp3",
  impidimp: "https://play.pokemonshowdown.com/audio/cries/impidimp.mp3",
  incineroar: "https://play.pokemonshowdown.com/audio/cries/incineroar.mp3",
  "indeedee-f": "https://play.pokemonshowdown.com/audio/cries/indeedee-f.mp3",
  indeedee: "https://play.pokemonshowdown.com/audio/cries/indeedee.mp3",
  infernape: "https://play.pokemonshowdown.com/audio/cries/infernape.mp3",
  inkay: "https://play.pokemonshowdown.com/audio/cries/inkay.mp3",
  inteleon: "https://play.pokemonshowdown.com/audio/cries/inteleon.mp3",
  ivysaur: "https://play.pokemonshowdown.com/audio/cries/ivysaur.mp3",
  jangmoo: "https://play.pokemonshowdown.com/audio/cries/jangmoo.mp3",
  jellicent: "https://play.pokemonshowdown.com/audio/cries/jellicent.mp3",
  jigglypuff: "https://play.pokemonshowdown.com/audio/cries/jigglypuff.mp3",
  jirachi: "https://play.pokemonshowdown.com/audio/cries/jirachi.mp3",
  jolteon: "https://play.pokemonshowdown.com/audio/cries/jolteon.mp3",
  joltik: "https://play.pokemonshowdown.com/audio/cries/joltik.mp3",
  jumbao: "https://play.pokemonshowdown.com/audio/cries/jumbao.mp3",
  jumpluff: "https://play.pokemonshowdown.com/audio/cries/jumpluff.mp3",
  justyke: "https://play.pokemonshowdown.com/audio/cries/justyke.mp3",
  jynx: "https://play.pokemonshowdown.com/audio/cries/jynx.mp3",
  kabuto: "https://play.pokemonshowdown.com/audio/cries/kabuto.mp3",
  kabutops: "https://play.pokemonshowdown.com/audio/cries/kabutops.mp3",
  kadabra: "https://play.pokemonshowdown.com/audio/cries/kadabra.mp3",
  kakuna: "https://play.pokemonshowdown.com/audio/cries/kakuna.mp3",
  "kangaskhan-mega":
    "https://play.pokemonshowdown.com/audio/cries/kangaskhan-mega.mp3",
  kangaskhan: "https://play.pokemonshowdown.com/audio/cries/kangaskhan.mp3",
  karrablast: "https://play.pokemonshowdown.com/audio/cries/karrablast.mp3",
  kartana: "https://play.pokemonshowdown.com/audio/cries/kartana.mp3",
  kecleon: "https://play.pokemonshowdown.com/audio/cries/kecleon.mp3",
  keldeo: "https://play.pokemonshowdown.com/audio/cries/keldeo.mp3",
  kerfluffle: "https://play.pokemonshowdown.com/audio/cries/kerfluffle.mp3",
  kingdra: "https://play.pokemonshowdown.com/audio/cries/kingdra.mp3",
  kingler: "https://play.pokemonshowdown.com/audio/cries/kingler.mp3",
  kirlia: "https://play.pokemonshowdown.com/audio/cries/kirlia.mp3",
  kitsunoh: "https://play.pokemonshowdown.com/audio/cries/kitsunoh.mp3",
  klang: "https://play.pokemonshowdown.com/audio/cries/klang.mp3",
  klefki: "https://play.pokemonshowdown.com/audio/cries/klefki.mp3",
  klink: "https://play.pokemonshowdown.com/audio/cries/klink.mp3",
  klinklang: "https://play.pokemonshowdown.com/audio/cries/klinklang.mp3",
  koffing: "https://play.pokemonshowdown.com/audio/cries/koffing.mp3",
  komala: "https://play.pokemonshowdown.com/audio/cries/komala.mp3",
  kommoo: "https://play.pokemonshowdown.com/audio/cries/kommoo.mp3",
  krabby: "https://play.pokemonshowdown.com/audio/cries/krabby.mp3",
  kricketot: "https://play.pokemonshowdown.com/audio/cries/kricketot.mp3",
  kricketune: "https://play.pokemonshowdown.com/audio/cries/kricketune.mp3",
  krilowatt: "https://play.pokemonshowdown.com/audio/cries/krilowatt.mp3",
  krokorok: "https://play.pokemonshowdown.com/audio/cries/krokorok.mp3",
  krookodile: "https://play.pokemonshowdown.com/audio/cries/krookodile.mp3",
  kubfu: "https://play.pokemonshowdown.com/audio/cries/kubfu.mp3",
  "kyogre-primal":
    "https://play.pokemonshowdown.com/audio/cries/kyogre-primal.mp3",
  kyogre: "https://play.pokemonshowdown.com/audio/cries/kyogre.mp3",
  "kyurem-black":
    "https://play.pokemonshowdown.com/audio/cries/kyurem-black.mp3",
  "kyurem-white":
    "https://play.pokemonshowdown.com/audio/cries/kyurem-white.mp3",
  kyurem: "https://play.pokemonshowdown.com/audio/cries/kyurem.mp3",
  lairon: "https://play.pokemonshowdown.com/audio/cries/lairon.mp3",
  lampent: "https://play.pokemonshowdown.com/audio/cries/lampent.mp3",
  "landorus-therian":
    "https://play.pokemonshowdown.com/audio/cries/landorus-therian.mp3",
  landorus: "https://play.pokemonshowdown.com/audio/cries/landorus.mp3",
  lanturn: "https://play.pokemonshowdown.com/audio/cries/lanturn.mp3",
  lapras: "https://play.pokemonshowdown.com/audio/cries/lapras.mp3",
  larvesta: "https://play.pokemonshowdown.com/audio/cries/larvesta.mp3",
  larvitar: "https://play.pokemonshowdown.com/audio/cries/larvitar.mp3",
  "latias-mega": "https://play.pokemonshowdown.com/audio/cries/latias-mega.mp3",
  latias: "https://play.pokemonshowdown.com/audio/cries/latias.mp3",
  "latios-mega": "https://play.pokemonshowdown.com/audio/cries/latios-mega.mp3",
  latios: "https://play.pokemonshowdown.com/audio/cries/latios.mp3",
  leafeon: "https://play.pokemonshowdown.com/audio/cries/leafeon.mp3",
  leavanny: "https://play.pokemonshowdown.com/audio/cries/leavanny.mp3",
  ledian: "https://play.pokemonshowdown.com/audio/cries/ledian.mp3",
  ledyba: "https://play.pokemonshowdown.com/audio/cries/ledyba.mp3",
  lickilicky: "https://play.pokemonshowdown.com/audio/cries/lickilicky.mp3",
  lickitung: "https://play.pokemonshowdown.com/audio/cries/lickitung.mp3",
  liepard: "https://play.pokemonshowdown.com/audio/cries/liepard.mp3",
  lileep: "https://play.pokemonshowdown.com/audio/cries/lileep.mp3",
  lilligant: "https://play.pokemonshowdown.com/audio/cries/lilligant.mp3",
  lillipup: "https://play.pokemonshowdown.com/audio/cries/lillipup.mp3",
  linoone: "https://play.pokemonshowdown.com/audio/cries/linoone.mp3",
  litleo: "https://play.pokemonshowdown.com/audio/cries/litleo.mp3",
  litten: "https://play.pokemonshowdown.com/audio/cries/litten.mp3",
  litwick: "https://play.pokemonshowdown.com/audio/cries/litwick.mp3",
  lombre: "https://play.pokemonshowdown.com/audio/cries/lombre.mp3",
  "lopunny-mega":
    "https://play.pokemonshowdown.com/audio/cries/lopunny-mega.mp3",
  lopunny: "https://play.pokemonshowdown.com/audio/cries/lopunny.mp3",
  lotad: "https://play.pokemonshowdown.com/audio/cries/lotad.mp3",
  loudred: "https://play.pokemonshowdown.com/audio/cries/loudred.mp3",
  "lucario-mega":
    "https://play.pokemonshowdown.com/audio/cries/lucario-mega.mp3",
  lucario: "https://play.pokemonshowdown.com/audio/cries/lucario.mp3",
  ludicolo: "https://play.pokemonshowdown.com/audio/cries/ludicolo.mp3",
  lugia: "https://play.pokemonshowdown.com/audio/cries/lugia.mp3",
  lumineon: "https://play.pokemonshowdown.com/audio/cries/lumineon.mp3",
  lunala: "https://play.pokemonshowdown.com/audio/cries/lunala.mp3",
  lunatone: "https://play.pokemonshowdown.com/audio/cries/lunatone.mp3",
  lurantis: "https://play.pokemonshowdown.com/audio/cries/lurantis.mp3",
  luvdisc: "https://play.pokemonshowdown.com/audio/cries/luvdisc.mp3",
  luxio: "https://play.pokemonshowdown.com/audio/cries/luxio.mp3",
  luxray: "https://play.pokemonshowdown.com/audio/cries/luxray.mp3",
  "lycanroc-dusk":
    "https://play.pokemonshowdown.com/audio/cries/lycanroc-dusk.mp3",
  "lycanroc-midnight":
    "https://play.pokemonshowdown.com/audio/cries/lycanroc-midnight.mp3",
  lycanroc: "https://play.pokemonshowdown.com/audio/cries/lycanroc.mp3",
  machamp: "https://play.pokemonshowdown.com/audio/cries/machamp.mp3",
  machoke: "https://play.pokemonshowdown.com/audio/cries/machoke.mp3",
  machop: "https://play.pokemonshowdown.com/audio/cries/machop.mp3",
  magby: "https://play.pokemonshowdown.com/audio/cries/magby.mp3",
  magcargo: "https://play.pokemonshowdown.com/audio/cries/magcargo.mp3",
  magearna: "https://play.pokemonshowdown.com/audio/cries/magearna.mp3",
  magikarp: "https://play.pokemonshowdown.com/audio/cries/magikarp.mp3",
  magmar: "https://play.pokemonshowdown.com/audio/cries/magmar.mp3",
  magmortar: "https://play.pokemonshowdown.com/audio/cries/magmortar.mp3",
  magnemite: "https://play.pokemonshowdown.com/audio/cries/magnemite.mp3",
  magneton: "https://play.pokemonshowdown.com/audio/cries/magneton.mp3",
  magnezone: "https://play.pokemonshowdown.com/audio/cries/magnezone.mp3",
  makuhita: "https://play.pokemonshowdown.com/audio/cries/makuhita.mp3",
  malaconda: "https://play.pokemonshowdown.com/audio/cries/malaconda.mp3",
  malamar: "https://play.pokemonshowdown.com/audio/cries/malamar.mp3",
  mamoswine: "https://play.pokemonshowdown.com/audio/cries/mamoswine.mp3",
  manaphy: "https://play.pokemonshowdown.com/audio/cries/manaphy.mp3",
  mandibuzz: "https://play.pokemonshowdown.com/audio/cries/mandibuzz.mp3",
  "manectric-mega":
    "https://play.pokemonshowdown.com/audio/cries/manectric-mega.mp3",
  manectric: "https://play.pokemonshowdown.com/audio/cries/manectric.mp3",
  mankey: "https://play.pokemonshowdown.com/audio/cries/mankey.mp3",
  mantine: "https://play.pokemonshowdown.com/audio/cries/mantine.mp3",
  mantyke: "https://play.pokemonshowdown.com/audio/cries/mantyke.mp3",
  maractus: "https://play.pokemonshowdown.com/audio/cries/maractus.mp3",
  mareanie: "https://play.pokemonshowdown.com/audio/cries/mareanie.mp3",
  mareep: "https://play.pokemonshowdown.com/audio/cries/mareep.mp3",
  marill: "https://play.pokemonshowdown.com/audio/cries/marill.mp3",
  marowak: "https://play.pokemonshowdown.com/audio/cries/marowak.mp3",
  marshadow: "https://play.pokemonshowdown.com/audio/cries/marshadow.mp3",
  marshtomp: "https://play.pokemonshowdown.com/audio/cries/marshtomp.mp3",
  masquerain: "https://play.pokemonshowdown.com/audio/cries/masquerain.mp3",
  "mawile-mega": "https://play.pokemonshowdown.com/audio/cries/mawile-mega.mp3",
  mawile: "https://play.pokemonshowdown.com/audio/cries/mawile.mp3",
  "medicham-mega":
    "https://play.pokemonshowdown.com/audio/cries/medicham-mega.mp3",
  medicham: "https://play.pokemonshowdown.com/audio/cries/medicham.mp3",
  meditite: "https://play.pokemonshowdown.com/audio/cries/meditite.mp3",
  meganium: "https://play.pokemonshowdown.com/audio/cries/meganium.mp3",
  melmetal: "https://play.pokemonshowdown.com/audio/cries/melmetal.mp3",
  meloetta: "https://play.pokemonshowdown.com/audio/cries/meloetta.mp3",
  meltan: "https://play.pokemonshowdown.com/audio/cries/meltan.mp3",
  meowstic: "https://play.pokemonshowdown.com/audio/cries/meowstic.mp3",
  meowth: "https://play.pokemonshowdown.com/audio/cries/meowth.mp3",
  mesprit: "https://play.pokemonshowdown.com/audio/cries/mesprit.mp3",
  "metagross-mega":
    "https://play.pokemonshowdown.com/audio/cries/metagross-mega.mp3",
  metagross: "https://play.pokemonshowdown.com/audio/cries/metagross.mp3",
  metang: "https://play.pokemonshowdown.com/audio/cries/metang.mp3",
  metapod: "https://play.pokemonshowdown.com/audio/cries/metapod.mp3",
  mew: "https://play.pokemonshowdown.com/audio/cries/mew.mp3",
  "mewtwo-megax":
    "https://play.pokemonshowdown.com/audio/cries/mewtwo-megax.mp3",
  "mewtwo-megay":
    "https://play.pokemonshowdown.com/audio/cries/mewtwo-megay.mp3",
  mewtwo: "https://play.pokemonshowdown.com/audio/cries/mewtwo.mp3",
  miasmaw: "https://play.pokemonshowdown.com/audio/cries/miasmaw.mp3",
  miasmite: "https://play.pokemonshowdown.com/audio/cries/miasmite.mp3",
  mienfoo: "https://play.pokemonshowdown.com/audio/cries/mienfoo.mp3",
  mienshao: "https://play.pokemonshowdown.com/audio/cries/mienshao.mp3",
  mightyena: "https://play.pokemonshowdown.com/audio/cries/mightyena.mp3",
  milcery: "https://play.pokemonshowdown.com/audio/cries/milcery.mp3",
  milotic: "https://play.pokemonshowdown.com/audio/cries/milotic.mp3",
  miltank: "https://play.pokemonshowdown.com/audio/cries/miltank.mp3",
  mimejr: "https://play.pokemonshowdown.com/audio/cries/mimejr.mp3",
  mimikyu: "https://play.pokemonshowdown.com/audio/cries/mimikyu.mp3",
  minccino: "https://play.pokemonshowdown.com/audio/cries/minccino.mp3",
  minior: "https://play.pokemonshowdown.com/audio/cries/minior.mp3",
  minun: "https://play.pokemonshowdown.com/audio/cries/minun.mp3",
  misdreavus: "https://play.pokemonshowdown.com/audio/cries/misdreavus.mp3",
  mismagius: "https://play.pokemonshowdown.com/audio/cries/mismagius.mp3",
  mollux: "https://play.pokemonshowdown.com/audio/cries/mollux.mp3",
  moltres: "https://play.pokemonshowdown.com/audio/cries/moltres.mp3",
  monferno: "https://play.pokemonshowdown.com/audio/cries/monferno.mp3",
  monohm: "https://play.pokemonshowdown.com/audio/cries/monohm.mp3",
  morelull: "https://play.pokemonshowdown.com/audio/cries/morelull.mp3",
  morgrem: "https://play.pokemonshowdown.com/audio/cries/morgrem.mp3",
  "morpeko-hangry":
    "https://play.pokemonshowdown.com/audio/cries/morpeko-hangry.mp3",
  morpeko: "https://play.pokemonshowdown.com/audio/cries/morpeko.mp3",
  mothim: "https://play.pokemonshowdown.com/audio/cries/mothim.mp3",
  mrmime: "https://play.pokemonshowdown.com/audio/cries/mrmime.mp3",
  mrrime: "https://play.pokemonshowdown.com/audio/cries/mrrime.mp3",
  mudbray: "https://play.pokemonshowdown.com/audio/cries/mudbray.mp3",
  mudkip: "https://play.pokemonshowdown.com/audio/cries/mudkip.mp3",
  mudsdale: "https://play.pokemonshowdown.com/audio/cries/mudsdale.mp3",
  muk: "https://play.pokemonshowdown.com/audio/cries/muk.mp3",
  mumbao: "https://play.pokemonshowdown.com/audio/cries/mumbao.mp3",
  munchlax: "https://play.pokemonshowdown.com/audio/cries/munchlax.mp3",
  munna: "https://play.pokemonshowdown.com/audio/cries/munna.mp3",
  murkrow: "https://play.pokemonshowdown.com/audio/cries/murkrow.mp3",
  musharna: "https://play.pokemonshowdown.com/audio/cries/musharna.mp3",
  naganadel: "https://play.pokemonshowdown.com/audio/cries/naganadel.mp3",
  natu: "https://play.pokemonshowdown.com/audio/cries/natu.mp3",
  naviathan: "https://play.pokemonshowdown.com/audio/cries/naviathan.mp3",
  "necrozma-dawnwings":
    "https://play.pokemonshowdown.com/audio/cries/necrozma-dawnwings.mp3",
  "necrozma-duskmane":
    "https://play.pokemonshowdown.com/audio/cries/necrozma-duskmane.mp3",
  "necrozma-ultra":
    "https://play.pokemonshowdown.com/audio/cries/necrozma-ultra.mp3",
  necrozma: "https://play.pokemonshowdown.com/audio/cries/necrozma.mp3",
  necturine: "https://play.pokemonshowdown.com/audio/cries/necturine.mp3",
  necturna: "https://play.pokemonshowdown.com/audio/cries/necturna.mp3",
  nickit: "https://play.pokemonshowdown.com/audio/cries/nickit.mp3",
  nidoking: "https://play.pokemonshowdown.com/audio/cries/nidoking.mp3",
  nidoqueen: "https://play.pokemonshowdown.com/audio/cries/nidoqueen.mp3",
  nidoran: "https://play.pokemonshowdown.com/audio/cries/nidoran.mp3",
  nidoranf: "https://play.pokemonshowdown.com/audio/cries/nidoranf.mp3",
  nidoranm: "https://play.pokemonshowdown.com/audio/cries/nidoranm.mp3",
  nidorina: "https://play.pokemonshowdown.com/audio/cries/nidorina.mp3",
  nidorino: "https://play.pokemonshowdown.com/audio/cries/nidorino.mp3",
  nihilego: "https://play.pokemonshowdown.com/audio/cries/nihilego.mp3",
  nincada: "https://play.pokemonshowdown.com/audio/cries/nincada.mp3",
  ninetales: "https://play.pokemonshowdown.com/audio/cries/ninetales.mp3",
  ninjask: "https://play.pokemonshowdown.com/audio/cries/ninjask.mp3",
  noctowl: "https://play.pokemonshowdown.com/audio/cries/noctowl.mp3",
  nohface: "https://play.pokemonshowdown.com/audio/cries/nohface.mp3",
  noibat: "https://play.pokemonshowdown.com/audio/cries/noibat.mp3",
  noivern: "https://play.pokemonshowdown.com/audio/cries/noivern.mp3",
  nosepass: "https://play.pokemonshowdown.com/audio/cries/nosepass.mp3",
  numel: "https://play.pokemonshowdown.com/audio/cries/numel.mp3",
  nuzleaf: "https://play.pokemonshowdown.com/audio/cries/nuzleaf.mp3",
  obstagoon: "https://play.pokemonshowdown.com/audio/cries/obstagoon.mp3",
  octillery: "https://play.pokemonshowdown.com/audio/cries/octillery.mp3",
  oddish: "https://play.pokemonshowdown.com/audio/cries/oddish.mp3",
  omanyte: "https://play.pokemonshowdown.com/audio/cries/omanyte.mp3",
  omastar: "https://play.pokemonshowdown.com/audio/cries/omastar.mp3",
  onix: "https://play.pokemonshowdown.com/audio/cries/onix.mp3",
  oranguru: "https://play.pokemonshowdown.com/audio/cries/oranguru.mp3",
  orbeetle: "https://play.pokemonshowdown.com/audio/cries/orbeetle.mp3",
  "oricorio-pau":
    "https://play.pokemonshowdown.com/audio/cries/oricorio-pau.mp3",
  "oricorio-pompom":
    "https://play.pokemonshowdown.com/audio/cries/oricorio-pompom.mp3",
  "oricorio-sensu":
    "https://play.pokemonshowdown.com/audio/cries/oricorio-sensu.mp3",
  oricorio: "https://play.pokemonshowdown.com/audio/cries/oricorio.mp3",
  oshawott: "https://play.pokemonshowdown.com/audio/cries/oshawott.mp3",
  pachirisu: "https://play.pokemonshowdown.com/audio/cries/pachirisu.mp3",
  pajantom: "https://play.pokemonshowdown.com/audio/cries/pajantom.mp3",
  palkia: "https://play.pokemonshowdown.com/audio/cries/palkia.mp3",
  palossand: "https://play.pokemonshowdown.com/audio/cries/palossand.mp3",
  palpitoad: "https://play.pokemonshowdown.com/audio/cries/palpitoad.mp3",
  pancham: "https://play.pokemonshowdown.com/audio/cries/pancham.mp3",
  pangoro: "https://play.pokemonshowdown.com/audio/cries/pangoro.mp3",
  panpour: "https://play.pokemonshowdown.com/audio/cries/panpour.mp3",
  pansage: "https://play.pokemonshowdown.com/audio/cries/pansage.mp3",
  pansear: "https://play.pokemonshowdown.com/audio/cries/pansear.mp3",
  paras: "https://play.pokemonshowdown.com/audio/cries/paras.mp3",
  parasect: "https://play.pokemonshowdown.com/audio/cries/parasect.mp3",
  passimian: "https://play.pokemonshowdown.com/audio/cries/passimian.mp3",
  patrat: "https://play.pokemonshowdown.com/audio/cries/patrat.mp3",
  pawniard: "https://play.pokemonshowdown.com/audio/cries/pawniard.mp3",
  pelipper: "https://play.pokemonshowdown.com/audio/cries/pelipper.mp3",
  perrserker: "https://play.pokemonshowdown.com/audio/cries/perrserker.mp3",
  persian: "https://play.pokemonshowdown.com/audio/cries/persian.mp3",
  petilil: "https://play.pokemonshowdown.com/audio/cries/petilil.mp3",
  phanpy: "https://play.pokemonshowdown.com/audio/cries/phanpy.mp3",
  phantump: "https://play.pokemonshowdown.com/audio/cries/phantump.mp3",
  pheromosa: "https://play.pokemonshowdown.com/audio/cries/pheromosa.mp3",
  phione: "https://play.pokemonshowdown.com/audio/cries/phione.mp3",
  pichu: "https://play.pokemonshowdown.com/audio/cries/pichu.mp3",
  "pidgeot-mega":
    "https://play.pokemonshowdown.com/audio/cries/pidgeot-mega.mp3",
  pidgeot: "https://play.pokemonshowdown.com/audio/cries/pidgeot.mp3",
  pidgeotto: "https://play.pokemonshowdown.com/audio/cries/pidgeotto.mp3",
  pidgey: "https://play.pokemonshowdown.com/audio/cries/pidgey.mp3",
  pidove: "https://play.pokemonshowdown.com/audio/cries/pidove.mp3",
  pignite: "https://play.pokemonshowdown.com/audio/cries/pignite.mp3",
  "pikachu-starter":
    "https://play.pokemonshowdown.com/audio/cries/pikachu-starter.mp3",
  pikachu: "https://play.pokemonshowdown.com/audio/cries/pikachu.mp3",
  pikipek: "https://play.pokemonshowdown.com/audio/cries/pikipek.mp3",
  piloswine: "https://play.pokemonshowdown.com/audio/cries/piloswine.mp3",
  pincurchin: "https://play.pokemonshowdown.com/audio/cries/pincurchin.mp3",
  pineco: "https://play.pokemonshowdown.com/audio/cries/pineco.mp3",
  "pinsir-mega": "https://play.pokemonshowdown.com/audio/cries/pinsir-mega.mp3",
  pinsir: "https://play.pokemonshowdown.com/audio/cries/pinsir.mp3",
  piplup: "https://play.pokemonshowdown.com/audio/cries/piplup.mp3",
  plasmanta: "https://play.pokemonshowdown.com/audio/cries/plasmanta.mp3",
  pluffle: "https://play.pokemonshowdown.com/audio/cries/pluffle.mp3",
  plusle: "https://play.pokemonshowdown.com/audio/cries/plusle.mp3",
  poipole: "https://play.pokemonshowdown.com/audio/cries/poipole.mp3",
  politoed: "https://play.pokemonshowdown.com/audio/cries/politoed.mp3",
  poliwag: "https://play.pokemonshowdown.com/audio/cries/poliwag.mp3",
  poliwhirl: "https://play.pokemonshowdown.com/audio/cries/poliwhirl.mp3",
  poliwrath: "https://play.pokemonshowdown.com/audio/cries/poliwrath.mp3",
  polteageist: "https://play.pokemonshowdown.com/audio/cries/polteageist.mp3",
  ponyta: "https://play.pokemonshowdown.com/audio/cries/ponyta.mp3",
  poochyena: "https://play.pokemonshowdown.com/audio/cries/poochyena.mp3",
  popplio: "https://play.pokemonshowdown.com/audio/cries/popplio.mp3",
  porygon: "https://play.pokemonshowdown.com/audio/cries/porygon.mp3",
  porygon2: "https://play.pokemonshowdown.com/audio/cries/porygon2.mp3",
  porygonz: "https://play.pokemonshowdown.com/audio/cries/porygonz.mp3",
  primarina: "https://play.pokemonshowdown.com/audio/cries/primarina.mp3",
  primeape: "https://play.pokemonshowdown.com/audio/cries/primeape.mp3",
  prinplup: "https://play.pokemonshowdown.com/audio/cries/prinplup.mp3",
  privatyke: "https://play.pokemonshowdown.com/audio/cries/privatyke.mp3",
  probopass: "https://play.pokemonshowdown.com/audio/cries/probopass.mp3",
  protowatt: "https://play.pokemonshowdown.com/audio/cries/protowatt.mp3",
  psyduck: "https://play.pokemonshowdown.com/audio/cries/psyduck.mp3",
  "pumpkaboo-super":
    "https://play.pokemonshowdown.com/audio/cries/pumpkaboo-super.mp3",
  pumpkaboo: "https://play.pokemonshowdown.com/audio/cries/pumpkaboo.mp3",
  pupitar: "https://play.pokemonshowdown.com/audio/cries/pupitar.mp3",
  purrloin: "https://play.pokemonshowdown.com/audio/cries/purrloin.mp3",
  purugly: "https://play.pokemonshowdown.com/audio/cries/purugly.mp3",
  pyroak: "https://play.pokemonshowdown.com/audio/cries/pyroak.mp3",
  pyroar: "https://play.pokemonshowdown.com/audio/cries/pyroar.mp3",
  pyukumuku: "https://play.pokemonshowdown.com/audio/cries/pyukumuku.mp3",
  quagsire: "https://play.pokemonshowdown.com/audio/cries/quagsire.mp3",
  quilava: "https://play.pokemonshowdown.com/audio/cries/quilava.mp3",
  quilladin: "https://play.pokemonshowdown.com/audio/cries/quilladin.mp3",
  qwilfish: "https://play.pokemonshowdown.com/audio/cries/qwilfish.mp3",
  raboot: "https://play.pokemonshowdown.com/audio/cries/raboot.mp3",
  raichu: "https://play.pokemonshowdown.com/audio/cries/raichu.mp3",
  raikou: "https://play.pokemonshowdown.com/audio/cries/raikou.mp3",
  ralts: "https://play.pokemonshowdown.com/audio/cries/ralts.mp3",
  rampardos: "https://play.pokemonshowdown.com/audio/cries/rampardos.mp3",
  rapidash: "https://play.pokemonshowdown.com/audio/cries/rapidash.mp3",
  raticate: "https://play.pokemonshowdown.com/audio/cries/raticate.mp3",
  rattata: "https://play.pokemonshowdown.com/audio/cries/rattata.mp3",
  "rayquaza-mega":
    "https://play.pokemonshowdown.com/audio/cries/rayquaza-mega.mp3",
  rayquaza: "https://play.pokemonshowdown.com/audio/cries/rayquaza.mp3",
  rebble: "https://play.pokemonshowdown.com/audio/cries/rebble.mp3",
  regice: "https://play.pokemonshowdown.com/audio/cries/regice.mp3",
  regidrago: "https://play.pokemonshowdown.com/audio/cries/regidrago.mp3",
  regieleki: "https://play.pokemonshowdown.com/audio/cries/regieleki.mp3",
  regigigas: "https://play.pokemonshowdown.com/audio/cries/regigigas.mp3",
  regirock: "https://play.pokemonshowdown.com/audio/cries/regirock.mp3",
  registeel: "https://play.pokemonshowdown.com/audio/cries/registeel.mp3",
  relicanth: "https://play.pokemonshowdown.com/audio/cries/relicanth.mp3",
  remoraid: "https://play.pokemonshowdown.com/audio/cries/remoraid.mp3",
  reshiram: "https://play.pokemonshowdown.com/audio/cries/reshiram.mp3",
  reuniclus: "https://play.pokemonshowdown.com/audio/cries/reuniclus.mp3",
  revenankh: "https://play.pokemonshowdown.com/audio/cries/revenankh.mp3",
  rhydon: "https://play.pokemonshowdown.com/audio/cries/rhydon.mp3",
  rhyhorn: "https://play.pokemonshowdown.com/audio/cries/rhyhorn.mp3",
  rhyperior: "https://play.pokemonshowdown.com/audio/cries/rhyperior.mp3",
  ribombee: "https://play.pokemonshowdown.com/audio/cries/ribombee.mp3",
  rillaboom: "https://play.pokemonshowdown.com/audio/cries/rillaboom.mp3",
  riolu: "https://play.pokemonshowdown.com/audio/cries/riolu.mp3",
  rockruff: "https://play.pokemonshowdown.com/audio/cries/rockruff.mp3",
  roggenrola: "https://play.pokemonshowdown.com/audio/cries/roggenrola.mp3",
  rolycoly: "https://play.pokemonshowdown.com/audio/cries/rolycoly.mp3",
  rookidee: "https://play.pokemonshowdown.com/audio/cries/rookidee.mp3",
  roselia: "https://play.pokemonshowdown.com/audio/cries/roselia.mp3",
  roserade: "https://play.pokemonshowdown.com/audio/cries/roserade.mp3",
  rotom: "https://play.pokemonshowdown.com/audio/cries/rotom.mp3",
  rowlet: "https://play.pokemonshowdown.com/audio/cries/rowlet.mp3",
  rufflet: "https://play.pokemonshowdown.com/audio/cries/rufflet.mp3",
  runerigus: "https://play.pokemonshowdown.com/audio/cries/runerigus.mp3",
  "sableye-mega":
    "https://play.pokemonshowdown.com/audio/cries/sableye-mega.mp3",
  sableye: "https://play.pokemonshowdown.com/audio/cries/sableye.mp3",
  "salamence-mega":
    "https://play.pokemonshowdown.com/audio/cries/salamence-mega.mp3",
  salamence: "https://play.pokemonshowdown.com/audio/cries/salamence.mp3",
  salandit: "https://play.pokemonshowdown.com/audio/cries/salandit.mp3",
  salazzle: "https://play.pokemonshowdown.com/audio/cries/salazzle.mp3",
  samurott: "https://play.pokemonshowdown.com/audio/cries/samurott.mp3",
  sandaconda: "https://play.pokemonshowdown.com/audio/cries/sandaconda.mp3",
  sandile: "https://play.pokemonshowdown.com/audio/cries/sandile.mp3",
  sandshrew: "https://play.pokemonshowdown.com/audio/cries/sandshrew.mp3",
  sandslash: "https://play.pokemonshowdown.com/audio/cries/sandslash.mp3",
  sandygast: "https://play.pokemonshowdown.com/audio/cries/sandygast.mp3",
  sawk: "https://play.pokemonshowdown.com/audio/cries/sawk.mp3",
  sawsbuck: "https://play.pokemonshowdown.com/audio/cries/sawsbuck.mp3",
  scatterbug: "https://play.pokemonshowdown.com/audio/cries/scatterbug.mp3",
  "sceptile-mega":
    "https://play.pokemonshowdown.com/audio/cries/sceptile-mega.mp3",
  sceptile: "https://play.pokemonshowdown.com/audio/cries/sceptile.mp3",
  "scizor-mega": "https://play.pokemonshowdown.com/audio/cries/scizor-mega.mp3",
  scizor: "https://play.pokemonshowdown.com/audio/cries/scizor.mp3",
  scolipede: "https://play.pokemonshowdown.com/audio/cries/scolipede.mp3",
  scorbunny: "https://play.pokemonshowdown.com/audio/cries/scorbunny.mp3",
  scrafty: "https://play.pokemonshowdown.com/audio/cries/scrafty.mp3",
  scraggy: "https://play.pokemonshowdown.com/audio/cries/scraggy.mp3",
  scratchet: "https://play.pokemonshowdown.com/audio/cries/scratchet.mp3",
  scyther: "https://play.pokemonshowdown.com/audio/cries/scyther.mp3",
  seadra: "https://play.pokemonshowdown.com/audio/cries/seadra.mp3",
  seaking: "https://play.pokemonshowdown.com/audio/cries/seaking.mp3",
  sealeo: "https://play.pokemonshowdown.com/audio/cries/sealeo.mp3",
  seedot: "https://play.pokemonshowdown.com/audio/cries/seedot.mp3",
  seel: "https://play.pokemonshowdown.com/audio/cries/seel.mp3",
  seismitoad: "https://play.pokemonshowdown.com/audio/cries/seismitoad.mp3",
  sentret: "https://play.pokemonshowdown.com/audio/cries/sentret.mp3",
  serperior: "https://play.pokemonshowdown.com/audio/cries/serperior.mp3",
  servine: "https://play.pokemonshowdown.com/audio/cries/servine.mp3",
  seviper: "https://play.pokemonshowdown.com/audio/cries/seviper.mp3",
  sewaddle: "https://play.pokemonshowdown.com/audio/cries/sewaddle.mp3",
  "sharpedo-mega":
    "https://play.pokemonshowdown.com/audio/cries/sharpedo-mega.mp3",
  sharpedo: "https://play.pokemonshowdown.com/audio/cries/sharpedo.mp3",
  "shaymin-sky": "https://play.pokemonshowdown.com/audio/cries/shaymin-sky.mp3",
  shaymin: "https://play.pokemonshowdown.com/audio/cries/shaymin.mp3",
  shedinja: "https://play.pokemonshowdown.com/audio/cries/shedinja.mp3",
  shelgon: "https://play.pokemonshowdown.com/audio/cries/shelgon.mp3",
  shellder: "https://play.pokemonshowdown.com/audio/cries/shellder.mp3",
  shellos: "https://play.pokemonshowdown.com/audio/cries/shellos.mp3",
  shelmet: "https://play.pokemonshowdown.com/audio/cries/shelmet.mp3",
  shieldon: "https://play.pokemonshowdown.com/audio/cries/shieldon.mp3",
  shiftry: "https://play.pokemonshowdown.com/audio/cries/shiftry.mp3",
  shiinotic: "https://play.pokemonshowdown.com/audio/cries/shiinotic.mp3",
  shinx: "https://play.pokemonshowdown.com/audio/cries/shinx.mp3",
  shroomish: "https://play.pokemonshowdown.com/audio/cries/shroomish.mp3",
  shuckle: "https://play.pokemonshowdown.com/audio/cries/shuckle.mp3",
  shuppet: "https://play.pokemonshowdown.com/audio/cries/shuppet.mp3",
  sigilyph: "https://play.pokemonshowdown.com/audio/cries/sigilyph.mp3",
  silcoon: "https://play.pokemonshowdown.com/audio/cries/silcoon.mp3",
  silicobra: "https://play.pokemonshowdown.com/audio/cries/silicobra.mp3",
  silvally: "https://play.pokemonshowdown.com/audio/cries/silvally.mp3",
  simipour: "https://play.pokemonshowdown.com/audio/cries/simipour.mp3",
  simisage: "https://play.pokemonshowdown.com/audio/cries/simisage.mp3",
  simisear: "https://play.pokemonshowdown.com/audio/cries/simisear.mp3",
  sinistea: "https://play.pokemonshowdown.com/audio/cries/sinistea.mp3",
  sirfetchd: "https://play.pokemonshowdown.com/audio/cries/sirfetchd.mp3",
  sizzlipede: "https://play.pokemonshowdown.com/audio/cries/sizzlipede.mp3",
  skarmory: "https://play.pokemonshowdown.com/audio/cries/skarmory.mp3",
  skiddo: "https://play.pokemonshowdown.com/audio/cries/skiddo.mp3",
  skiploom: "https://play.pokemonshowdown.com/audio/cries/skiploom.mp3",
  skitty: "https://play.pokemonshowdown.com/audio/cries/skitty.mp3",
  skorupi: "https://play.pokemonshowdown.com/audio/cries/skorupi.mp3",
  skrelp: "https://play.pokemonshowdown.com/audio/cries/skrelp.mp3",
  skuntank: "https://play.pokemonshowdown.com/audio/cries/skuntank.mp3",
  skwovet: "https://play.pokemonshowdown.com/audio/cries/skwovet.mp3",
  slaking: "https://play.pokemonshowdown.com/audio/cries/slaking.mp3",
  slakoth: "https://play.pokemonshowdown.com/audio/cries/slakoth.mp3",
  sliggoo: "https://play.pokemonshowdown.com/audio/cries/sliggoo.mp3",
  "slowbro-mega":
    "https://play.pokemonshowdown.com/audio/cries/slowbro-mega.mp3",
  slowbro: "https://play.pokemonshowdown.com/audio/cries/slowbro.mp3",
  slowking: "https://play.pokemonshowdown.com/audio/cries/slowking.mp3",
  "slowpoke-galar":
    "https://play.pokemonshowdown.com/audio/cries/slowpoke-galar.mp3",
  slowpoke: "https://play.pokemonshowdown.com/audio/cries/slowpoke.mp3",
  slugma: "https://play.pokemonshowdown.com/audio/cries/slugma.mp3",
  slurpuff: "https://play.pokemonshowdown.com/audio/cries/slurpuff.mp3",
  smeargle: "https://play.pokemonshowdown.com/audio/cries/smeargle.mp3",
  smogecko: "https://play.pokemonshowdown.com/audio/cries/smogecko.mp3",
  smoguana: "https://play.pokemonshowdown.com/audio/cries/smoguana.mp3",
  smokomodo: "https://play.pokemonshowdown.com/audio/cries/smokomodo.mp3",
  smoochum: "https://play.pokemonshowdown.com/audio/cries/smoochum.mp3",
  snaelstrom: "https://play.pokemonshowdown.com/audio/cries/snaelstrom.mp3",
  sneasel: "https://play.pokemonshowdown.com/audio/cries/sneasel.mp3",
  snivy: "https://play.pokemonshowdown.com/audio/cries/snivy.mp3",
  snom: "https://play.pokemonshowdown.com/audio/cries/snom.mp3",
  snorlax: "https://play.pokemonshowdown.com/audio/cries/snorlax.mp3",
  snorunt: "https://play.pokemonshowdown.com/audio/cries/snorunt.mp3",
  snover: "https://play.pokemonshowdown.com/audio/cries/snover.mp3",
  snubbull: "https://play.pokemonshowdown.com/audio/cries/snubbull.mp3",
  snugglow: "https://play.pokemonshowdown.com/audio/cries/snugglow.mp3",
  sobble: "https://play.pokemonshowdown.com/audio/cries/sobble.mp3",
  solgaleo: "https://play.pokemonshowdown.com/audio/cries/solgaleo.mp3",
  solosis: "https://play.pokemonshowdown.com/audio/cries/solosis.mp3",
  solotl: "https://play.pokemonshowdown.com/audio/cries/solotl.mp3",
  solrock: "https://play.pokemonshowdown.com/audio/cries/solrock.mp3",
  spearow: "https://play.pokemonshowdown.com/audio/cries/spearow.mp3",
  spectrier: "https://play.pokemonshowdown.com/audio/cries/spectrier.mp3",
  spewpa: "https://play.pokemonshowdown.com/audio/cries/spewpa.mp3",
  spheal: "https://play.pokemonshowdown.com/audio/cries/spheal.mp3",
  spinarak: "https://play.pokemonshowdown.com/audio/cries/spinarak.mp3",
  spinda: "https://play.pokemonshowdown.com/audio/cries/spinda.mp3",
  spiritomb: "https://play.pokemonshowdown.com/audio/cries/spiritomb.mp3",
  spoink: "https://play.pokemonshowdown.com/audio/cries/spoink.mp3",
  spritzee: "https://play.pokemonshowdown.com/audio/cries/spritzee.mp3",
  squirtle: "https://play.pokemonshowdown.com/audio/cries/squirtle.mp3",
  stakataka: "https://play.pokemonshowdown.com/audio/cries/stakataka.mp3",
  stantler: "https://play.pokemonshowdown.com/audio/cries/stantler.mp3",
  staraptor: "https://play.pokemonshowdown.com/audio/cries/staraptor.mp3",
  staravia: "https://play.pokemonshowdown.com/audio/cries/staravia.mp3",
  starly: "https://play.pokemonshowdown.com/audio/cries/starly.mp3",
  starmie: "https://play.pokemonshowdown.com/audio/cries/starmie.mp3",
  staryu: "https://play.pokemonshowdown.com/audio/cries/staryu.mp3",
  "steelix-mega":
    "https://play.pokemonshowdown.com/audio/cries/steelix-mega.mp3",
  steelix: "https://play.pokemonshowdown.com/audio/cries/steelix.mp3",
  steenee: "https://play.pokemonshowdown.com/audio/cries/steenee.mp3",
  stonjourner: "https://play.pokemonshowdown.com/audio/cries/stonjourner.mp3",
  stoutland: "https://play.pokemonshowdown.com/audio/cries/stoutland.mp3",
  stratagem: "https://play.pokemonshowdown.com/audio/cries/stratagem.mp3",
  stufful: "https://play.pokemonshowdown.com/audio/cries/stufful.mp3",
  stunfisk: "https://play.pokemonshowdown.com/audio/cries/stunfisk.mp3",
  stunky: "https://play.pokemonshowdown.com/audio/cries/stunky.mp3",
  sudowoodo: "https://play.pokemonshowdown.com/audio/cries/sudowoodo.mp3",
  suicune: "https://play.pokemonshowdown.com/audio/cries/suicune.mp3",
  sunflora: "https://play.pokemonshowdown.com/audio/cries/sunflora.mp3",
  sunkern: "https://play.pokemonshowdown.com/audio/cries/sunkern.mp3",
  surskit: "https://play.pokemonshowdown.com/audio/cries/surskit.mp3",
  swablu: "https://play.pokemonshowdown.com/audio/cries/swablu.mp3",
  swadloon: "https://play.pokemonshowdown.com/audio/cries/swadloon.mp3",
  swalot: "https://play.pokemonshowdown.com/audio/cries/swalot.mp3",
  "swampert-mega":
    "https://play.pokemonshowdown.com/audio/cries/swampert-mega.mp3",
  swampert: "https://play.pokemonshowdown.com/audio/cries/swampert.mp3",
  swanna: "https://play.pokemonshowdown.com/audio/cries/swanna.mp3",
  swellow: "https://play.pokemonshowdown.com/audio/cries/swellow.mp3",
  swinub: "https://play.pokemonshowdown.com/audio/cries/swinub.mp3",
  swirlix: "https://play.pokemonshowdown.com/audio/cries/swirlix.mp3",
  swirlpool: "https://play.pokemonshowdown.com/audio/cries/swirlpool.mp3",
  swoobat: "https://play.pokemonshowdown.com/audio/cries/swoobat.mp3",
  syclant: "https://play.pokemonshowdown.com/audio/cries/syclant.mp3",
  syclar: "https://play.pokemonshowdown.com/audio/cries/syclar.mp3",
  sylveon: "https://play.pokemonshowdown.com/audio/cries/sylveon.mp3",
  tactite: "https://play.pokemonshowdown.com/audio/cries/tactite.mp3",
  taillow: "https://play.pokemonshowdown.com/audio/cries/taillow.mp3",
  talonflame: "https://play.pokemonshowdown.com/audio/cries/talonflame.mp3",
  tangela: "https://play.pokemonshowdown.com/audio/cries/tangela.mp3",
  tangrowth: "https://play.pokemonshowdown.com/audio/cries/tangrowth.mp3",
  tapubulu: "https://play.pokemonshowdown.com/audio/cries/tapubulu.mp3",
  tapufini: "https://play.pokemonshowdown.com/audio/cries/tapufini.mp3",
  tapukoko: "https://play.pokemonshowdown.com/audio/cries/tapukoko.mp3",
  tapulele: "https://play.pokemonshowdown.com/audio/cries/tapulele.mp3",
  tauros: "https://play.pokemonshowdown.com/audio/cries/tauros.mp3",
  teddiursa: "https://play.pokemonshowdown.com/audio/cries/teddiursa.mp3",
  tentacool: "https://play.pokemonshowdown.com/audio/cries/tentacool.mp3",
  tentacruel: "https://play.pokemonshowdown.com/audio/cries/tentacruel.mp3",
  tepig: "https://play.pokemonshowdown.com/audio/cries/tepig.mp3",
  terrakion: "https://play.pokemonshowdown.com/audio/cries/terrakion.mp3",
  thievul: "https://play.pokemonshowdown.com/audio/cries/thievul.mp3",
  throh: "https://play.pokemonshowdown.com/audio/cries/throh.mp3",
  "thundurus-therian":
    "https://play.pokemonshowdown.com/audio/cries/thundurus-therian.mp3",
  thundurus: "https://play.pokemonshowdown.com/audio/cries/thundurus.mp3",
  thwackey: "https://play.pokemonshowdown.com/audio/cries/thwackey.mp3",
  timburr: "https://play.pokemonshowdown.com/audio/cries/timburr.mp3",
  tirtouga: "https://play.pokemonshowdown.com/audio/cries/tirtouga.mp3",
  togedemaru: "https://play.pokemonshowdown.com/audio/cries/togedemaru.mp3",
  togekiss: "https://play.pokemonshowdown.com/audio/cries/togekiss.mp3",
  "togepi'": "https://play.pokemonshowdown.com/audio/cries/togepi'.mp3",
  togepi: "https://play.pokemonshowdown.com/audio/cries/togepi.mp3",
  togetic: "https://play.pokemonshowdown.com/audio/cries/togetic.mp3",
  tomohawk: "https://play.pokemonshowdown.com/audio/cries/tomohawk.mp3",
  torchic: "https://play.pokemonshowdown.com/audio/cries/torchic.mp3",
  torkoal: "https://play.pokemonshowdown.com/audio/cries/torkoal.mp3",
  "tornadus-therian":
    "https://play.pokemonshowdown.com/audio/cries/tornadus-therian.mp3",
  tornadus: "https://play.pokemonshowdown.com/audio/cries/tornadus.mp3",
  torracat: "https://play.pokemonshowdown.com/audio/cries/torracat.mp3",
  torterra: "https://play.pokemonshowdown.com/audio/cries/torterra.mp3",
  totodile: "https://play.pokemonshowdown.com/audio/cries/totodile.mp3",
  toucannon: "https://play.pokemonshowdown.com/audio/cries/toucannon.mp3",
  toxapex: "https://play.pokemonshowdown.com/audio/cries/toxapex.mp3",
  toxel: "https://play.pokemonshowdown.com/audio/cries/toxel.mp3",
  toxicroak: "https://play.pokemonshowdown.com/audio/cries/toxicroak.mp3",
  "toxtricity-lowkey":
    "https://play.pokemonshowdown.com/audio/cries/toxtricity-lowkey.mp3",
  toxtricity: "https://play.pokemonshowdown.com/audio/cries/toxtricity.mp3",
  tranquill: "https://play.pokemonshowdown.com/audio/cries/tranquill.mp3",
  trapinch: "https://play.pokemonshowdown.com/audio/cries/trapinch.mp3",
  treecko: "https://play.pokemonshowdown.com/audio/cries/treecko.mp3",
  trevenant: "https://play.pokemonshowdown.com/audio/cries/trevenant.mp3",
  tropius: "https://play.pokemonshowdown.com/audio/cries/tropius.mp3",
  trubbish: "https://play.pokemonshowdown.com/audio/cries/trubbish.mp3",
  trumbeak: "https://play.pokemonshowdown.com/audio/cries/trumbeak.mp3",
  tsareena: "https://play.pokemonshowdown.com/audio/cries/tsareena.mp3",
  turtonator: "https://play.pokemonshowdown.com/audio/cries/turtonator.mp3",
  turtwig: "https://play.pokemonshowdown.com/audio/cries/turtwig.mp3",
  tympole: "https://play.pokemonshowdown.com/audio/cries/tympole.mp3",
  tynamo: "https://play.pokemonshowdown.com/audio/cries/tynamo.mp3",
  typenull: "https://play.pokemonshowdown.com/audio/cries/typenull.mp3",
  typhlosion: "https://play.pokemonshowdown.com/audio/cries/typhlosion.mp3",
  "tyranitar-mega":
    "https://play.pokemonshowdown.com/audio/cries/tyranitar-mega.mp3",
  tyranitar: "https://play.pokemonshowdown.com/audio/cries/tyranitar.mp3",
  tyrantrum: "https://play.pokemonshowdown.com/audio/cries/tyrantrum.mp3",
  tyrogue: "https://play.pokemonshowdown.com/audio/cries/tyrogue.mp3",
  tyrunt: "https://play.pokemonshowdown.com/audio/cries/tyrunt.mp3",
  umbreon: "https://play.pokemonshowdown.com/audio/cries/umbreon.mp3",
  unfezant: "https://play.pokemonshowdown.com/audio/cries/unfezant.mp3",
  unown: "https://play.pokemonshowdown.com/audio/cries/unown.mp3",
  ursaring: "https://play.pokemonshowdown.com/audio/cries/ursaring.mp3",
  "urshifu-rapidstrike":
    "https://play.pokemonshowdown.com/audio/cries/urshifu-rapidstrike.mp3",
  urshifu: "https://play.pokemonshowdown.com/audio/cries/urshifu.mp3",
  uxie: "https://play.pokemonshowdown.com/audio/cries/uxie.mp3",
  vanillish: "https://play.pokemonshowdown.com/audio/cries/vanillish.mp3",
  vanillite: "https://play.pokemonshowdown.com/audio/cries/vanillite.mp3",
  vanilluxe: "https://play.pokemonshowdown.com/audio/cries/vanilluxe.mp3",
  vaporeon: "https://play.pokemonshowdown.com/audio/cries/vaporeon.mp3",
  venipede: "https://play.pokemonshowdown.com/audio/cries/venipede.mp3",
  venomoth: "https://play.pokemonshowdown.com/audio/cries/venomoth.mp3",
  venonat: "https://play.pokemonshowdown.com/audio/cries/venonat.mp3",
  "venusaur-mega":
    "https://play.pokemonshowdown.com/audio/cries/venusaur-mega.mp3",
  venusaur: "https://play.pokemonshowdown.com/audio/cries/venusaur.mp3",
  vespiquen: "https://play.pokemonshowdown.com/audio/cries/vespiquen.mp3",
  vibrava: "https://play.pokemonshowdown.com/audio/cries/vibrava.mp3",
  victini: "https://play.pokemonshowdown.com/audio/cries/victini.mp3",
  victreebel: "https://play.pokemonshowdown.com/audio/cries/victreebel.mp3",
  vigoroth: "https://play.pokemonshowdown.com/audio/cries/vigoroth.mp3",
  vikavolt: "https://play.pokemonshowdown.com/audio/cries/vikavolt.mp3",
  vileplume: "https://play.pokemonshowdown.com/audio/cries/vileplume.mp3",
  virizion: "https://play.pokemonshowdown.com/audio/cries/virizion.mp3",
  vivillon: "https://play.pokemonshowdown.com/audio/cries/vivillon.mp3",
  volbeat: "https://play.pokemonshowdown.com/audio/cries/volbeat.mp3",
  volcanion: "https://play.pokemonshowdown.com/audio/cries/volcanion.mp3",
  volcarona: "https://play.pokemonshowdown.com/audio/cries/volcarona.mp3",
  volkraken: "https://play.pokemonshowdown.com/audio/cries/volkraken.mp3",
  volkritter: "https://play.pokemonshowdown.com/audio/cries/volkritter.mp3",
  voltorb: "https://play.pokemonshowdown.com/audio/cries/voltorb.mp3",
  voodoll: "https://play.pokemonshowdown.com/audio/cries/voodoll.mp3",
  voodoom: "https://play.pokemonshowdown.com/audio/cries/voodoom.mp3",
  vullaby: "https://play.pokemonshowdown.com/audio/cries/vullaby.mp3",
  vulpix: "https://play.pokemonshowdown.com/audio/cries/vulpix.mp3",
  wailmer: "https://play.pokemonshowdown.com/audio/cries/wailmer.mp3",
  wailord: "https://play.pokemonshowdown.com/audio/cries/wailord.mp3",
  walrein: "https://play.pokemonshowdown.com/audio/cries/walrein.mp3",
  wartortle: "https://play.pokemonshowdown.com/audio/cries/wartortle.mp3",
  watchog: "https://play.pokemonshowdown.com/audio/cries/watchog.mp3",
  weavile: "https://play.pokemonshowdown.com/audio/cries/weavile.mp3",
  weedle: "https://play.pokemonshowdown.com/audio/cries/weedle.mp3",
  weepinbell: "https://play.pokemonshowdown.com/audio/cries/weepinbell.mp3",
  weezing: "https://play.pokemonshowdown.com/audio/cries/weezing.mp3",
  whimsicott: "https://play.pokemonshowdown.com/audio/cries/whimsicott.mp3",
  whirlipede: "https://play.pokemonshowdown.com/audio/cries/whirlipede.mp3",
  whiscash: "https://play.pokemonshowdown.com/audio/cries/whiscash.mp3",
  whismur: "https://play.pokemonshowdown.com/audio/cries/whismur.mp3",
  wigglytuff: "https://play.pokemonshowdown.com/audio/cries/wigglytuff.mp3",
  wimpod: "https://play.pokemonshowdown.com/audio/cries/wimpod.mp3",
  wingull: "https://play.pokemonshowdown.com/audio/cries/wingull.mp3",
  "wishiwashi-school":
    "https://play.pokemonshowdown.com/audio/cries/wishiwashi-school.mp3",
  wishiwashi: "https://play.pokemonshowdown.com/audio/cries/wishiwashi.mp3",
  wobbuffet: "https://play.pokemonshowdown.com/audio/cries/wobbuffet.mp3",
  woobat: "https://play.pokemonshowdown.com/audio/cries/woobat.mp3",
  wooloo: "https://play.pokemonshowdown.com/audio/cries/wooloo.mp3",
  wooper: "https://play.pokemonshowdown.com/audio/cries/wooper.mp3",
  wormadam: "https://play.pokemonshowdown.com/audio/cries/wormadam.mp3",
  wurmple: "https://play.pokemonshowdown.com/audio/cries/wurmple.mp3",
  wynaut: "https://play.pokemonshowdown.com/audio/cries/wynaut.mp3",
  xatu: "https://play.pokemonshowdown.com/audio/cries/xatu.mp3",
  xerneas: "https://play.pokemonshowdown.com/audio/cries/xerneas.mp3",
  xurkitree: "https://play.pokemonshowdown.com/audio/cries/xurkitree.mp3",
  yamask: "https://play.pokemonshowdown.com/audio/cries/yamask.mp3",
  yamper: "https://play.pokemonshowdown.com/audio/cries/yamper.mp3",
  yanma: "https://play.pokemonshowdown.com/audio/cries/yanma.mp3",
  yanmega: "https://play.pokemonshowdown.com/audio/cries/yanmega.mp3",
  yungoos: "https://play.pokemonshowdown.com/audio/cries/yungoos.mp3",
  yveltal: "https://play.pokemonshowdown.com/audio/cries/yveltal.mp3",
  "zacian-crowned":
    "https://play.pokemonshowdown.com/audio/cries/zacian-crowned.mp3",
  zacian: "https://play.pokemonshowdown.com/audio/cries/zacian.mp3",
  "zamazenta-crowned":
    "https://play.pokemonshowdown.com/audio/cries/zamazenta-crowned.mp3",
  zamazenta: "https://play.pokemonshowdown.com/audio/cries/zamazenta.mp3",
  zangoose: "https://play.pokemonshowdown.com/audio/cries/zangoose.mp3",
  zapdos: "https://play.pokemonshowdown.com/audio/cries/zapdos.mp3",
  zarude: "https://play.pokemonshowdown.com/audio/cries/zarude.mp3",
  zebstrika: "https://play.pokemonshowdown.com/audio/cries/zebstrika.mp3",
  zekrom: "https://play.pokemonshowdown.com/audio/cries/zekrom.mp3",
  zeraora: "https://play.pokemonshowdown.com/audio/cries/zeraora.mp3",
  zigzagoon: "https://play.pokemonshowdown.com/audio/cries/zigzagoon.mp3",
  zoroark: "https://play.pokemonshowdown.com/audio/cries/zoroark.mp3",
  zorua: "https://play.pokemonshowdown.com/audio/cries/zorua.mp3",
  zubat: "https://play.pokemonshowdown.com/audio/cries/zubat.mp3",
  zweilous: "https://play.pokemonshowdown.com/audio/cries/zweilous.mp3",
  "zygarde-10": "https://play.pokemonshowdown.com/audio/cries/zygarde-10.mp3",
  "zygarde-complete":
    "https://play.pokemonshowdown.com/audio/cries/zygarde-complete.mp3",
  zygarde: "https://play.pokemonshowdown.com/audio/cries/zygarde.mp3",
};
